apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
    namespace: monitoring
stringData:
    pushover_api_token: ENC[AES256_GCM,data:EMNV3nS05clabo2/dpYMaGVa6f7YDHdjJjcJRwzM,iv:UUQY0WVRLJdcWAfvv4cL7gVxeMzKFJh8eKEocPo2Sfo=,tag:V/bFDntAHeXAE4jgzIH6wQ==,type:str]
    pushover_user_key: ENC[AES256_GCM,data:YaBxrhT8lKcFmmP0VDrHQ5gGTXWk93YpkIY2GiP0,iv:wzMzfxH8R8Jc4SwA0jLvXk+yv0gKPpGJZDb05e5Alzs=,tag:bda3uJbS685VliYmcHD5BA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cyfh7x9qffez0eutk5c928m42k3kftjjwn8qveledrzl83y3544s5yjm8q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZTnpURGQxSk1qVmxSblNz
            WWFNVFdNOHpUTS8xbERtb25WUFRKd2dMV0FNCi9QejVXUG5lNGY4M0huZDRVdVRk
            QmcwMjZ1NkJmVHA5TGs3dEJWSjU2dFEKLS0tIHVTSlFJQkNDZGRQVlFLUGYrYk5R
            Mlp1cUUrRzMxMG1qUndxQ0k2WDBvVHcKOa26mz1WAjccm382e1wbt/8aEdSDvojy
            FVvLRsV4jCd9bwoElR04AlvBCE/lLlPUCG4UchPWByhPsYepNTssXQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T05:46:50Z"
    mac: ENC[AES256_GCM,data:GV1DK4w3uf/OTGPm40UUuWzsxIVoBrKeYo3iQPHXDaYBqY3eqzqO84M78hltqKdxygeKgIrvtd1dfuWABQztPwI9d777IEVlP9VVlO/HgwqDiYyyxy30ndN/RS8xdBffdz3K7Djzp9p7coD0MJpcAGf0OE1r+t0GDU43T8Nnxak=,iv:aP++MyebJCf+Zqr0gi9OGhvnN4cweDW9uRUjJEUS6E0=,tag:EuI2oNWAGYxMg/gISkESNg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
