apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
    namespace: monitoring
stringData:
    pushover_api_token: ENC[AES256_GCM,data:ql2DKVyKApI3xhjujrUznfR9vh53lDfqxuclBw81,iv:U3zRUm/TC3644IMVcaBhQs9bFlxCzGRsrXEcHurI7L4=,tag:kt9M0Mxas5IqSKA4XepExA==,type:str]
    pushover_user_key: ENC[AES256_GCM,data:QkgavTF99F/ISUdyiuyxOZnAc1TmKcZ6oRI88W7y,iv:7gl840JTYzy2QYsiyIueGcKPpUpt1qpRKxlPYt0ImCk=,tag:kfMw4kSoc46tLGl96QhicA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cyfh7x9qffez0eutk5c928m42k3kftjjwn8qveledrzl83y3544s5yjm8q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZTnpURGQxSk1qVmxSblNz
            WWFNVFdNOHpUTS8xbERtb25WUFRKd2dMV0FNCi9QejVXUG5lNGY4M0huZDRVdVRk
            QmcwMjZ1NkJmVHA5TGs3dEJWSjU2dFEKLS0tIHVTSlFJQkNDZGRQVlFLUGYrYk5R
            Mlp1cUUrRzMxMG1qUndxQ0k2WDBvVHcKOa26mz1WAjccm382e1wbt/8aEdSDvojy
            FVvLRsV4jCd9bwoElR04AlvBCE/lLlPUCG4UchPWByhPsYepNTssXQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-31T02:53:31Z"
    mac: ENC[AES256_GCM,data:Iv5vmQPgd8KX6KC+b1BtqcANgqU/Kjhkw+IAaK4HcmFctM4jLzscbY/QUvrMoX6asSVTAtWW4gdSi/ihq7lRyiGkYtwtT/gmxRcT/exiB7LyqTc+/nzbpctYd5Y8by5awn4H34YyEyWgznUE51AZvM4+gwPN/sQWO4ylg/su/qY=,iv:/eJGK36IiTh0V9Uh8spZF1kikUYbjQnG2V/9jiGYlIc=,tag:s8R2hAZcpDaVvHSrrt5EXg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
