---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./backube.yaml
  - ./bitnami.yaml
  - ./piraeus.yaml
  - ./bjw-s.yaml
  - ./cilium.yaml
  - ./external-dns.yaml
  - ./external-secrets.yaml
  - ./grafana.yaml
  - ./ingress-nginx.yaml
  - ./intel.yaml
  - ./jetstack.yaml
  - ./k8s-gateway.yaml
  - ./kubernetes-sigs-metrics-server.yaml
  - ./kubernetes-sigs-nfd.yaml
  - ./open-webui.yaml
  - ./postfinance.yaml
  - ./prometheus-community.yaml
  - ./stakater.yaml
  - ./cloudnative-pg.yaml
  - ./immich.yaml
  - ./synology-csi.yaml
