---
collections:
  - name: community.general
    version: 10.7.6
  - name: community.sops
    version: 2.0.1
  - name: community.postgresql
    version: 3.10.2
roles:
  - name: geerlingguy.postgresql
    version: 3.5.2
