---
collections:
  - name: community.general
    version: 10.3.0
  - name: community.sops
    version: 2.0.1
  - name: community.postgresql
    version: 4.2.0
roles:
  - name: geerlingguy.postgresql
    version: 3.5.2
