---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: esphome
  namespace: flux-system
spec:
  path: ./cluster/apps/default/esphome/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
  wait: false
  interval: 1h
  timeout: 15m
